
from tkinter import *
from math import sqrt

root = Tk()

canvas = Canvas(root, width='600', height='600')
canvas.pack()

rows = int(input("number of rows generated by triangels: "))

a = 600 // rows
h = int(a*sqrt(3)/2)

def tri(x,y, a, h):
    tri = canvas.create_polygon(x, y, x + a, y, x + a/2, y - h, outline='black', fill='white', width=1)

for i in range(rows):
    for j in range(rows-i):
        tri(j*a+i*a/2, 600-(i*h), a, h)

root.mainloop()